### ISSUE TITLE
parsing fails on empty multiline arrays

### ISSUE THREAD

**Issue by strcrzy** [jm/toml#21]
hi, i'm writing an example/default config with comments in toml, and it seems to choke your parser. i'm using toml 0.0.4.  

``` toml
[example]
  empty_array = [] # works
  empty_multi_line_array = [
           # fails
  ]
```

The exception i get is:

```
Failed to match sequence (ALL_SPACE (KEY_GROUP / KEY_VALUE / COMMENT_LINE){0, } ALL_SPACE) at line 2 char 3.
`- Extra input after last repetition at line 2 char 3.
   `- Failed to match [ \t\r\n] at line 2 char 3.
```

i believe it is valid TOML, per the spec:
"Arrays can also be multiline. So in addition to ignoring whitespace, arrays also ignore newlines between the brackets. Terminating commas are ok before the closing bracket."

i'm interested in digging into the parser/grammar myself and making a PR, but before I did I just wanted to make sure this was a valid issue and that you would be interested in a fix
