### ISSUE TITLE
Too accepting of malformed input

### ISSUE THREAD

**Issue by cespare** [jm/toml#5]
Thanks for the great gem. I'm looking forward to the next gem release because I'm using the git version to get TOML generation.

This parser accepts several kinds of input specifically described as invalid at https://github.com/mojombo/toml. I discovered these errors using [toml-test](https://github.com/BurntSushi/toml-test); see the test methodology and output in [this gist](https://gist.github.com/cespare/5052442).

I ran tests against the latest head of master (479353753fc71173e9a8f778a9c3c20a0f92d189)
1. Accepts arrays with mixed types, which are not valid toml.
   
   Spec:
   
   >  No, you can't mix data types, that's stupid.
   
   Example TOML:
   
   ``` toml
   arrays-and-ints =  [1, ["Arrays are not integers."]]
   ```
2. Accepts mutually duplicated keys/keygroups.
   
   Spec:
   
   > Be careful not to overwrite previous keys. That's dumb. And should produce an error.
   
   Example 1:
   
   ``` toml
   [fruit]
   type = "apple"
   
   [fruit.type]
   apple = "yes"
   ```
   
   Example 2:
   
   ``` toml
   [a]
   [a]
   ```
   
   Example 3:
   
   ``` toml
   dupe = false
   dupe = true
   ```
